name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install yarn
        run: npm i -g yarn
      - name: Install project dependencies
        run: yarn install
      - name: Run tests
        run: yarn test -- --watchAll=false --silent
      - name: Lint
        run: yarn lint
      - name: Compile
        run: tsc
